### ISSUE TITLE
Где бродит жирный боров?

### ISSUE THREAD

**Issue by Purpl3Br1ck** [quadyyyy/belgorod-pois#1]
Ты слышишь этот звук?
Это Пиглины вокруг!
Зазевался на секунду -
Твоё золото сопрут.
Что тебе нужно?
Копытце позолоти,
Забирай что дали
И быстренько вали (Быстрей!)
Где бродит жирный боров,
В бастионах нет законов.
Незер станет для нас домом,
Хоть и полон адских стонов. (Аууу!)
Я хаваю свинину,
Хоть и сам свиньёй являюсь,
Меч воткну я тебе в спину,
Вижу злато - извиняюсь
Пока брюхо не вспорото, башня не расколота
Неси мне золото, парень, неси мне золото!
Адское пламя с молоду обжигает холодом,
Мне нужно золото, отдай мне своё золото,
А после прочь из города, нам не нужно повода,
А нужно золото, нужно твоё золото!
Жить по-свински дорого, закусывая боровом.
Неси мне золото, отдай своё золото!
Если броня твоя не золотая
То тебя не залатают, беги!
В сундуках наших так много тайн,
Но всё, что ты нажил лутает Пиглин
Если броня твоя не золотая
То тебя не залатают, беги!
В сундуках наших так много тайн,
Но всё, что ты нажил лутает Пиглин
Постой, родной!
Не такой уж ты простой,
Стоит в броне золотой,
Сразу видно что герой.
Прости нас, братка,
За свинские повадки,
В аду живём мы так-то
Тут условия не сладкие.
Ты пойми нас, ладно, (Ладно)
Детей кормить надо. (Надо)
Сбежали б мы из ада, (Зада)
Но воздух хуже яда!
Мне в жизни всё отрадно,
Люблю, как лава булькает (Буль-буль!)
В одной держу я злато,
Другой в крови по рульку.

**Comment by quadyyyy** [comment]
ок

**Comment by Purpl3Br1ck** [comment]
Неправильно. В бастионе, где нет законов, где незер станет для нас домом, хоть и полон адских стонов, он хавает свинину, хоть и сам свиньёй является, меч воткнёт он тебе в спину, видит злато, извиняется
